language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake
    packages:
      - cmake
      - cmake-data
      - gfortran

os:
  - linux
  - osx

script:
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DLAPACKE=ON -DCBLAS=ON .
  - ctest -D ExperimentalStart
  - ctest -D ExperimentalConfigure
  - ctest -D ExperimentalBuild -j2
  - ctest -D ExperimentalTest --schedule-random -j2 --output-on-failure --timeout 100
  - ctest -D ExperimentalSubmit
  - make install -j2
